# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/user/application_security/sast/#available-cicd-variables
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure/
# Dependency Scanning customization: https://docs.gitlab.com/user/application_security/dependency_scanning/#customizing-analyzer-behavior
# Container Scanning customization: https://docs.gitlab.com/user/application_security/container_scanning/#customizing-analyzer-behavior
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ci/variables/#cicd-variable-precedence
stages:
  - test
  - secret-detection

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

cmake-build-and-test:
  rules:
    - changes:
      - /*.{cpp, h, c}
      - CMakeLists.txt
  stage: test
  image: gcc:13
  before_script:
    - apt-get update && apt-get install -y cmake libgtest-dev
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build -j$(nproc)
    - cd build
    - ./libexcessive_tests
  artifacts:
    when: always
    paths:
      - build
    expire_in: 1 week

sast:
  stage: test

secret_detection:
  stage: secret-detection