name: CI

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' || ${{ matrix.os }} == 'ubuntu-24.04-arm' ]]; then
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev
        elif [[ ${{ matrix.os }} == 'macos-latest' || ${{ matrix.os }} == 'macos-15-intel' ]]; then
          brew install cmake googletest
        fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DLIBEXCESSIVE_BUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target libexcessive_tests

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        # Ensure tests can find any required resources or handle directory changes if needed.
        ./libexcessive_tests
