name: PR Preview

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docs/wiki/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare Docs
        run: |
          mkdir -p _site
          cp docs/wiki/*.md _site/
          echo "title: LibExcessive: High-Performance Persistent Datastructures in C++" > _site/_config.yml
          echo "baseurl: /pr-${{ github.event.number }}" >> _site/_config.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy-preview:
    if: github.event.pull_request.head.repo.fork == false
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
